# Generated by Django 5.0.6 on 2025-11-11 00:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miAppCalificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='imports/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Cargando'), ('VALIDATED', 'Calidando (esperando de validacion)'), ('IMPORTING', 'Importando.....'), ('IMPORTED', 'Importado'), ('CANCELLED', 'Proceso cancelado'), ('FAILED', 'Cago mano')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Rol')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion del Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña_hash', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('pais_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_del_pais', to='miAppCalificacion.pais', verbose_name='Rol del Sistema')),
                ('rol_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_rol', to='miAppUsuario.rol', verbose_name='Rol del Sistema')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='miAppUsuario.usuario')),
            ],
            options={
                'verbose_name': 'Histórico de Usuario',
                'verbose_name_plural': 'Históricos de Usuarios',
                'ordering': ['-modified_at'],
            },
        ),
    ]
