# Generated by Django 5.0.6 on 2025-11-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAppUsuario', '0002_usuario_fecha_creacion_usuario_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña_hash',
            field=models.CharField(max_length=255),
        ),
    ]
