# Generated by Django 5.0.6 on 2025-11-12 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAppCalificacion', '0002_alter_moneda_options_alter_pais_options_and_more'),
        ('miAppUsuario', '0003_alter_usuario_contraseña_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_del_pais', to='miAppCalificacion.pais', verbose_name='País de Usuario'),
        ),
    ]
