# Generated by Django 5.0.6 on 2025-11-11 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iso', models.CharField(max_length=10, unique=True, verbose_name='Código ISO')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre de la Moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de País')),
                ('codigo_iso', models.CharField(max_length=10, unique=True, verbose_name='Codigo ISO de País')),
                ('moneda_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='países', to='miAppCalificacion.moneda', verbose_name='Moneda Local')),
            ],
        ),
    ]
