# Generated by Django 5.0.6 on 2025-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_fin_periodo', models.DateField()),
                ('monto_impuesto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto del Impuesto')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
            },
        ),
        migrations.CreateModel(
            name='EmpresaSubsidiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_legal', models.CharField(max_length=255, unique=True)),
                ('identificacion_fiscal', models.CharField(max_length=50, unique=True)),
                ('actividad_principal', models.CharField(max_length=255)),
                ('regimen_fiscal', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Empresa Subsidiaria',
                'verbose_name_plural': 'Empresas subsidiarias',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iso', models.CharField(max_length=3, unique=True, verbose_name='Código ISO')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Moneda')),
                ('simbolo', models.CharField(max_length=10, null=True, verbose_name='Símbolo')),
                ('es_moneda_base', models.BooleanField(default=False, verbose_name='Moneda Base para Tasa de Cambio')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['codigo_iso'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del País')),
                ('codigo_iso', models.CharField(max_length=3, unique=True, verbose_name='Código ISO')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='TasaDeCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_tasa', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Valor de la Tasa')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
            },
        ),
    ]
