# Generated by Django 5.0.6 on 2025-11-11 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAppCalificacion', '0001_initial'),
        ('miAppUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneda',
            options={'ordering': ['codigo_iso'], 'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AddField(
            model_name='moneda',
            name='es_moneda_base',
            field=models.BooleanField(default=False, verbose_name='Moneda Base para Tasa de Cambio'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='simbolo',
            field=models.CharField(max_length=10, null=True, verbose_name='Símbolo'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='codigo_iso',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código ISO'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de Moneda'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo_iso',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código ISO'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='moneda_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miAppCalificacion.moneda', verbose_name='Moneda Local'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del País'),
        ),
        migrations.CreateModel(
            name='EmpresaSubsidiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_legal', models.CharField(max_length=255, unique=True)),
                ('identificacion_fiscal', models.CharField(max_length=50, unique=True)),
                ('actividad_principal', models.CharField(max_length=255)),
                ('regimen_fiscal', models.CharField(max_length=100)),
                ('pais_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miAppCalificacion.pais')),
            ],
            options={
                'verbose_name': 'Empresa Subsidiaria',
                'verbose_name_plural': 'Empresas subsidiarias',
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_fin_periodo', models.DateField()),
                ('monto_impuesto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto del Impuesto')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_creadas', to='miAppUsuario.usuario', verbose_name='Usuario Creador')),
                ('usuario_modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_modificadas', to='miAppUsuario.usuario', verbose_name='Usuario Modificador')),
                ('empresa_subsidiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAppCalificacion.empresasubsidiaria', verbose_name='Empresa Subsidiaria')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'unique_together': {('empresa_subsidiaria', 'fecha_inicio_periodo')},
            },
        ),
        migrations.CreateModel(
            name='TasaDeCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_tasa', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Valor de la Tasa')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_como_destino', to='miAppCalificacion.moneda', verbose_name='Moneda Destino')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_como_origen', to='miAppCalificacion.moneda', verbose_name='Moneda Origen')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'unique_together': {('moneda_origen', 'moneda_destino', 'fecha')},
            },
        ),
    ]
