# Generated by Django 5.0.6 on 2025-11-14 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miAppCalificacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='usuario_modificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='empresa_subsidiaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAppCalificacion.empresasubsidiaria', verbose_name='Empresa Subsidiaria'),
        ),
        migrations.AddField(
            model_name='pais',
            name='moneda_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miAppCalificacion.moneda', verbose_name='Moneda Local'),
        ),
        migrations.AddField(
            model_name='empresasubsidiaria',
            name='pais_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miAppCalificacion.pais'),
        ),
        migrations.AddField(
            model_name='tasadecambio',
            name='moneda_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_como_destino', to='miAppCalificacion.moneda', verbose_name='Moneda Destino'),
        ),
        migrations.AddField(
            model_name='tasadecambio',
            name='moneda_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_como_origen', to='miAppCalificacion.moneda', verbose_name='Moneda Origen'),
        ),
        migrations.AlterUniqueTogether(
            name='calificaciontributaria',
            unique_together={('empresa_subsidiaria', 'fecha_inicio_periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='tasadecambio',
            unique_together={('moneda_origen', 'moneda_destino', 'fecha')},
        ),
    ]
